# 로깅설정 log4j2 적용이 안되어서 그냥 logback 사용..
#logging:
#  config: classpath:config/log4j2.yml

# 서버설정
server:
  servlet:
    context-path: /
  ssl:
    enabled: false

# Spring설정
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource: # DB설정
    url: jdbc:h2:mem:mileage;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: admin
    password: adminpwd123

  jpa:  # JPA설정
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  messages: # Message설정
    basename: messages/message
    encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2_console
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
