# log4j2 설정파일
Configuration:
#  name: log4j2
#  status: warn

  Appenders:
    Console:
      name: console
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

  Loggers:
    logger:
      - name: com.example.mileage
        level: debug
        additivity: false
        AppenderRef:
          - ref: console
      - name: org.hibernate.type.descriptor.sql.BasicBinder
        level: trace
        additivity: false
        AppenderRef:
          - ref: console
      - name: org.hibernate.SQL
        level: debug
        additivity: false
        AppenderRef:
          - ref: console
    Root:
      level: debug
      AppenderRef:
        - ref: console

